openapi: 3.0.0
info:
  title: HeNex V3
  description: This collection includes all the APIs of version 3 for HeNex
  version: 1.0.0
servers:
  - url: https://api.diem-platform.com
paths:
  /api/v3/data/henexmarketresultsdemand/2021/10/28/20:
    get:
      tags:
        - General
      summary: GR Market-Market Results Demand
      description: no
      summary: GR Market-Market Results Demand
      x-codegen-request-body-name: rest_service14request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/rest_service14request"
            example:
              class: CRETE LOAD
              direction: 1
              market: DAM
              meta:
                requestParams:
                  year: '2021'
                  month: '10'
                  day: '28'
                  duration: '20'
                  class: CRETE LOAD
                  market: DAM
                  direction: BUY
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: OK
          headers:
            X-Powered-By:
              schema:
                type: string
              example:
                value: Express
            Access-Control-Allow-Origin:
              schema:
                type: string
              example:
                value: '*'
            Access-Control-Allow-Headers:
              schema:
                type: string
              example:
                value: Origin, X-Requested-With, Content-Type, Accept, x-auth-token
            Access-Control-Allow-Methods:
              schema:
                type: string
              example:
                value: POST, GET, PUT, DELETE, OPTIONS
            Content-Type:
              schema:
                type: string
              example:
                value: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
              example:
                value: '35366'
            ETag:
              schema:
                type: string
              example:
                value: W/"8a26-vv+DakRYAD+mV8yxppq+WutTHDM"
            Date:
              schema:
                type: string
              example:
                value: Sun, 15 May 2022 18:44:59 GMT
            Connection:
              schema:
                type: string
              example:
                value: keep-alive
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/REST_ServiceResponse94"
              example:
                $schema: http://json-schema.org/draft-04/schema#
                type: object
                properties:
                  meta:
                    type: object
                    properties:
                      requestParams:
                        type: object
                        properties:
                          year:
                            type: string
                          month:
                            type: string
                          day:
                            type: string
                          duration:
                            type: string
                          class:
                            type: string
                          market:
                            type: string
                          direction:
                            type: string
                      timezone:
                        type: string
                      offeringName:
                        type: string
                      updatedOn:
                        type: string
                      source:
                        type: string
                  data:
                    type: object
                    properties:
                      Load:
                        type: array
                        items:
                          type: object
                          properties:
                            DateTime:
                              type: string
                            value:
                              type: number
                            ResolutionCode:
                              type: string
                            uom:
                              type: string
                          required:
                            - DateTime
                            - value
                            - ResolutionCode
                            - uom
  /api/v3/data/henexmarketresultsborderschedulesall/2020/10/28/20:
    get:
      tags:
        - General
      summary: GR Market-Market Results BorderSchedules All Interconnections
      description: no
      summary: GR Market-Market Results BorderSchedules All Interconnections
      x-codegen-request-body-name: rest_service149request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/rest_service149request"
            example:
              class: Imports
              direction: 0
              market: DAM
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: OK
          headers:
            X-Powered-By:
              schema:
                type: string
              example:
                value: Express
            Access-Control-Allow-Origin:
              schema:
                type: string
              example:
                value: '*'
            Access-Control-Allow-Headers:
              schema:
                type: string
              example:
                value: Origin, X-Requested-With, Content-Type, Accept, x-auth-token
            Access-Control-Allow-Methods:
              schema:
                type: string
              example:
                value: POST, GET, PUT, DELETE, OPTIONS
            Content-Type:
              schema:
                type: string
              example:
                value: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
              example:
                value: '133325'
            ETag:
              schema:
                type: string
              example:
                value: W/"208cd-HymOKp2P0H6fVT8CK8RfoteFYGY"
            Date:
              schema:
                type: string
              example:
                value: Sun, 15 May 2022 21:14:04 GMT
            Connection:
              schema:
                type: string
              example:
                value: keep-alive
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/REST_ServiceResponse224"
              example:
                $schema: http://json-schema.org/draft-04/schema#
                type: object
                properties:
                  meta:
                    type: object
                    properties:
                      requestParams:
                        type: object
                        properties:
                          year:
                            type: string
                          month:
                            type: string
                          day:
                            type: string
                          duration:
                            type: string
                          class:
                            type: string
                          market:
                            type: string
                          direction:
                            type: string
                      timezone:
                        type: string
                      offeringName:
                        type: string
                      updatedOn:
                        type: string
                      source:
                        type: string
                  data:
                    type: object
                    properties:
                      MK-GR:
                        type: array
                        items:
                          type: object
                          properties:
                            DateTime:
                              type: string
                            value:
                              type: number
                            ResolutionCode:
                              type: string
                            uom:
                              type: string
                          required:
                            - DateTime
                            - value
                            - ResolutionCode
                            - uom
                      TR-GR:
                        type: array
                        items:
                          type: object
                          properties:
                            DateTime:
                              type: string
                            value:
                              type: number
                            ResolutionCode:
                              type: string
                            uom:
                              type: string
                          required:
                            - DateTime
                            - value
                            - ResolutionCode
                            - uom
                      AL-GR:
                        type: array
                        items:
                          type: object
                          properties:
                            DateTime:
                              type: string
                            value:
                              type: number
                            ResolutionCode:
                              type: string
                            uom:
                              type: string
                          required:
                            - DateTime
                            - value
                            - ResolutionCode
                            - uom
                      BG-GR:
                        type: array
                        items:
                          type: object
                          properties:
                            DateTime:
                              type: string
                            value:
                              type: number
                            ResolutionCode:
                              type: string
                            uom:
                              type: string
                          required:
                            - DateTime
                            - value
                            - ResolutionCode
                            - uom
                      IT-GR:
                        type: array
                        items:
                          type: object
                          properties:
                            DateTime:
                              type: string
                            value:
                              type: number
                            ResolutionCode:
                              type: string
                            uom:
                              type: string
                          required:
                            - DateTime
                            - value
                            - ResolutionCode
                            - uom
  /api/v3/data/henexmarketresultsborderschedules/2021/10/29/3:
    get:
      tags:
        - General
      summary: GR Market-Market Results BorderSchedules
      description: no
      summary: GR Market-Market Results BorderSchedules
      x-codegen-request-body-name: rest_service347request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/rest_service347request"
            example:
              interconnection: AL-GR
              direction: 0
              market: DAM
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: Successful response
          content:
  /api/v3/data/henexmarketresultsperproductiontechnology/2020/10/28/500:
    get:
      tags:
        - General
      summary: GR Market-Market Results Per Production Technology
      description: no
      summary: GR Market-Market Results Per Production Technology
      x-codegen-request-body-name: rest_service372request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/rest_service372request"
            example:
              technology: CRETE CONVENTIONAL
              direction: 0
              market: DAM
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: Successful response
          content:
  /api/v3/data/henexmarketresultsperproductiontechnologypermarket/2020/10/28/2000:
    get:
      tags:
        - General
      summary: GR Market-Market Results Per Production Technology Per Market
      description: no
      summary: GR Market-Market Results Per Production Technology Per Market
      x-codegen-request-body-name: rest_service397request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/rest_service397request"
            example:
              technology: CRETE CONVENTIONAL
              direction: 0
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: Successful response
          content:
  /api/v3/data/henexmarketresultspricespermarket/2020/10/28/20:
    get:
      tags:
        - General
      summary: GR Market-Market Results Prices Per Market
      description: no
      summary: GR Market-Market Results Prices Per Market
      x-codegen-request-body-name: rest_service421request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/rest_service421request"
            example:
              direction: 0
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: Successful response
          content:
  /api/v3/data/henexmarketresultsprices/2020/10/28/5:
    get:
      tags:
        - General
      summary: GR Market-Market Results Prices
      description: no
      summary: GR Market-Market Results Prices
      x-codegen-request-body-name: rest_service444request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/rest_service444request"
            example:
              direction: 0
              market: DAM
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: Successful response
          content:
  /api/v3/data/henexpremarketresultsborderschedules/2020/10/28/5:
    get:
      tags:
        - General
      summary: GR Market-PreMarket Results BorderSchedules
      description: no
      summary: GR Market-PreMarket Results BorderSchedules
      x-codegen-request-body-name: rest_service468request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/rest_service468request"
            example:
              direction: 0
              interconnection: AL-GR
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: Successful response
          content:
  /api/v3/data/henexpremarketresultsborderschedulesall/2020/10/28/5:
    get:
      tags:
        - General
      summary: GR Market-PreMarket Results BorderSchedules All Interconnections
      description: no
      summary: GR Market-PreMarket Results BorderSchedules All Interconnections
      x-codegen-request-body-name: rest_service492request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/rest_service492request"
            example:
              direction: 0
              class: Import
              market: DAM
              timezone: CET
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: Successful response
          content:
  /api/v3/data/henexpremarketresultsdemand/2020/10/28/5:
    get:
      tags:
        - General
      summary: GR Market-PreMarket Results Demand
      description: no
      summary: GR Market-PreMarket Results Demand
      x-codegen-request-body-name: rest_service518request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/rest_service518request"
            example:
              direction: 1
              class: LV
              market: DAM
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
        - name: format
          in: query
          schema:
            type: string
          example: csv
        - name: max
          in: query
          schema:
            type: integer
          example: '10'
      responses:
        '200':
          description: Successful response
          content:
  /api/v3/data/henexpremarketsummaryperproductiontechnology/2020/10/28/5:
    get:
      tags:
        - General
      summary: GR Market-PreMarket Summary per Production Technology
      description: no
      summary: GR Market-PreMarket Summary per Production Technology
      x-codegen-request-body-name: rest_service553request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/rest_service553request"
            example:
              direction: 0
              technology: Lignite
              market: DAM
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: Successful response
          content:
  /api/v3/data/henexmarketresultsdemandpermarket/2020/10/28/500:
    get:
      tags:
        - General
      summary: GR Market-Market Results Demand Per Market
      description: no
      summary: GR Market-Market Results Demand Per Market
      x-codegen-request-body-name: rest_service578request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/rest_service578request"
            example:
              direction: 0
              class: HV
      parameters:
        - name: x-auth-key
          in: header
          schema:
            type: string
          example: ASLDKJASDJK2534S
      responses:
        '200':
          description: Successful response
          content:
components:
  schemas:
     rest_service14request:
       type: object
     rest_service149request:
       type: object
     rest_service347request:
       type: object
     rest_service372request:
       type: object
     rest_service397request:
       type: object
     rest_service421request:
       type: object
     rest_service444request:
       type: object
     rest_service468request:
       type: object
     rest_service492request:
       type: object
     rest_service518request:
       type: object
     rest_service553request:
       type: object
     rest_service578request:
       type: object
     REST_ServiceResponse94:
       type: object
     REST_ServiceResponse224:
       type: object
